import type { MetadataRoute } from "next";

/**
 * Lets Betapet be installed to a phone's home screen and opened as its own app.
 *
 * `display: "standalone"` is the point of it: an installed game has no browser address bar at
 * all, so the bar cannot appear or disappear mid-gesture and shift the board under a finger. The
 * playing view is already pinned so that a browser tab never scrolls the document
 * (`ui-design.md` section 41); installing removes the address bar from the picture entirely.
 *
 * The icons are generated by `scripts/generate-icons.mts` from the game's own tile colours.
 * "maskable" lets Android crop the icon to whatever shape its launcher uses without eating the
 * letter — the tile is drawn well inside the safe area for that reason.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Betapet",
    short_name: "Betapet",
    description:
      "Ett Alfapet-inspirerat brädspel för två spelare på samma enhet.",
    lang: "sv",
    start_url: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#fffefb",
    theme_color: "#fffefb",
    icons: [
      {
        src: "/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
